### GET ALL PRODUCTS

GET http://localhost:4000/tasks HTTP/1.1

### GET SINGLE PRODUCT

GET http://localhost:4000/tasks/619350889179065611cda302 HTTP/1.1


### ADD ITEM

POST http://localhost:4000/tasks HTTP/1.1
Content-Type: application/json

{
    "description": "abs work",
    "exercise": "abs",
    "duration": "21",
    "date": "11"
}

### UPDATE ITEM

PUT http://localhost:4000/tasks/619350889179065611cda302 HTTP/1.1
Content-Type: application/json

{
    "description": "Updated title" 
}


### DELETE ITEM

DELETE http://localhost:4000/tasks/619350889179065611cda302 HTTP/1.1 